remote_theme: niklasbuschmann/contrast@v3.0

title: "A long title that will take space away from the menu"
#author: "Person One & Person Two"
description: "This is some research we did"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
baseurl: /testrepo/
# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {file: "page1.md", title: "Page lel"}
  - {file: "page2.md"}
  - {file: "md with a space.md", title: "Me Short"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-remote-theme
